baseURL = "https://blog.geunho.dev"
languageCode = "en-us"
title = "Blog · 김근호(Kim, Geunho)"
author = "김근호(Kim, Geunho)"
#theme = "black-and-light"

pygmentsStyle = "bw"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableGitInfo = true
FootnoteReturnLinkContents = "[↑]"
googleAnalytics = "UA-146312497-1"

[params]
  sitename = "Blog · 김근호(Kim, Geunho)"
  disableWebFonts = false
  avatar = "/avatar.jpg"
  socialId = "geunho"
  mail = "geunho.dev@gmail.com"

[[menu.main]]
    name = "About"
    url  = "/about"
[[menu.main]]
    name = "Posts"
    url  = "/posts"
#[[menu.main]]
#    name = "Resume"
#    url  = "/resume"
[[menu.main]]
    name = "Thoughts"
    url  = "/thoughts"
[[menu.main]]
    title = "TIL"
    name = "TIL"
    url  = "/til"
    