baseURL = "https://blog.geunho.dev"
languageCode = "en-us"
title = "Blog · 김근호(Kim, Geunho)"
author = "김근호(Kim, Geunho)"
theme = "black-and-light"

pygmentsstyle = "bw"
pygmentscodefences = true



[params]
  sitename = "Blog · 김근호(Kim, Geunho)"
  disableWebFonts = false
  avatar = "/avatar.jpg"
  socialId = "geunho"
  mail = "geunho.dev@gmail.com"

[[menu.main]]
    name = "About"
    url  = "/about"
[[menu.main]]
    name = "Posts"
    url  = "/posts"
[[menu.main]]
    name = "Resume"
    url  = "/resume"
[[menu.main]]
    name = "Thoughts"
    url  = "/thoughts"